name: Deploy Blazor to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Clean old /docs
      run: rm -rf docs && mkdir docs

    - name: Publish Blazor App to /docs
      run: dotnet publish ./moosharp.dev.csproj -c Release -o docs

    - name: Check if build succeeded
      run: test -f docs/index.html

    - name: Add CNAME, .nojekyll, 404.html
      run: |
        echo "moosharp.dev" > docs/CNAME
        echo "" > docs/.nojekyll
        cp docs/index.html docs/404.html

    - name: Commit and Push /docs
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs
        git commit -m "Deploy Blazor to /docs" || echo "No changes to commit"
        git push
